url: https://pmichaeldev.github.io/
baseurl: .

# Site settings
title: Philip Michael - Software Developer
email: phil-mik@hotmail.com
description: "Avid Programmer. Inspired Software Developer. Passionate Gamer and Game Developer. I also hold a Bachelor's of Computer Science!"


# Build settings
markdown: kramdown
permalink: pretty