url: https://pmichaeldev.github.io/
baseurl: .

# Site settings
title: Philip Michael - Software Developer
email: phil-mik@hotmail.com
description: "Avid Software Engineer. AWS Certified Developer - Associate."


# Build settings
markdown: kramdown
permalink: pretty